name: yordamchiapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  smooth_page_indicator: ^1.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonds/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonds/Poppins-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonds/Montserrat-VariableFont_wght.ttf



